### ISSUE TITLE
Upgrade to 11.0 SP9

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/my-recent-items#1] opened 2017-10-02 19:07 UTC
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by AngelaIp** [comment] 2018-01-04 17:22
I can confirm that this project still works in general in 11SP9 for FF, IE and Chrome (but Chrome seems to be a little bit slow). 
It´s a useful project! Users ask me about these kind of feature several times.

Some remarks:
-	The first import package is not needed when doing the import in 11SP9.
-	The last package fails and is probable not necessary at all.
-	Package 1/2 do the job
-	Beware import package “3-Configuration Data”. It overrides the classification structure of Part, Document and CAD.

**Comment by EliJDonahue** [comment] 2018-01-06 00:00
I've fixed the Configuration data issue (Issue #3) and the delete error (Issue #2). 

The fixes have been merged and the documentation is updated for release [v4](https://github.com/ArasLabs/my-recent-items/releases/tag/v4). 

I forgot to check the last optional package before releasing though, so that may have to be removed/fixed in a v4.1.

**Comment by AngelaIp** [comment] 2018-01-09 08:00
Another hint that is relevant for one or the other. Package “3-Configuration Data” also overrides the default setting for the Parameters tab.

**Comment by EliJDonahue** [comment] 2018-01-26 15:49
That should also be resolved in PR #5.

**Comment by EliJDonahue** [comment] 2018-01-26 15:49
Closing this issue since v4 supports Aras 11 SP9.

**Closed as completed by EliJDonahue** 2018-01-26 15:49 UTC
Labels: Help Wanted, Type: Upgrade
